AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  TweetGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: tweetget # file name
      Runtime: go1.x
      CodeUri: lambda/build
      Timeout: 300
      AutoPublishAlias: latest
  S3UploadLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: s3upload # file name
      Runtime: go1.x
      CodeUri: lambda/build
      Timeout: 300
      AutoPublishAlias: latest
      Policies:
        - S3CrudPolicy:
            BucketName: twittermap.dekokun.info
        - {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "s3:PutObjectAcl",
                ],
                "Resource": ["arn:aws:s3:::twittermap.dekokun.info/*"]
              }
            ]
          }
  TwitterS3UploadStepFunction:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString:
        !Sub
        - |-
          {
            "StartAt": "FirstState",
            "States": {
              "FirstState": {
                "Type": "Task",
                "Resource": "${TweetGetLambdaArn}",
                "Retry": [
                  {
                    "ErrorEquals": [ "States.ALL" ],
                    "IntervalSeconds": 10,
                    "MaxAttempts": 3,
                    "BackoffRate": 2
                  }
                ],
                "Next": "TweetGetDoneState"
              },
                "TweetGetDoneState": {
                "Type": "Task",
                "Resource": "${S3UploadLambdaArn}",
                "Retry": [
                  {
                    "ErrorEquals": [ "States.ALL" ],
                    "IntervalSeconds": 10,
                    "MaxAttempts": 3,
                    "BackoffRate": 2
                  }
                ],
                "End": true
                }
            }
          }
        - {S3UploadLambdaArn: !GetAtt [ S3UploadLambda, Arn ], TweetGetLambdaArn: !GetAtt [ TweetGetLambda, Arn ]}
      RoleArn: !GetAtt [TwitterS3UploadStepFunctionRole, Arn]
  TwitterS3UploadStepFunctionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: [!GetAtt [S3UploadLambda, Arn], !GetAtt [TweetGetLambda, Arn]]
  TwitterS3UploadStepFunctionCloudWatchEvent:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: 'cron(*/20 * * * ? *)'
      State: ENABLED
      Targets:
        - Arn: !Ref TwitterS3UploadStepFunction
          Id: twitter-s3upload-stepfunction
          RoleArn: !GetAtt [TwitterS3UploadStepFunctionCloudWatchEventRole, Arn]
  TwitterS3UploadStepFunctionCloudWatchEventRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - events.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: [!Ref TwitterS3UploadStepFunction]
