AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  JsonS3UploadLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda-go # file name
      Runtime: go1.x
      CodeUri: lambda/build
      Timeout: 300
      AutoPublishAlias: latest
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
      Policies:
        - S3CrudPolicy:
            BucketName: twittermap.dekokun.info
  StepFunction:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: hoge
      DefinitionString:
        !Sub
        - |-
          {
            "StartAt": "HelloWorld",
            "States": {
              "HelloWorld": {
                "Type": "Task",
                "Resource": "${JsonS3UploadLambdaArn}",
                "End": true
              }
            }
          }
        - {JsonS3UploadLambdaArn: !GetAtt [ JsonS3UploadLambda, Arn ]}
      RoleArn: !GetAtt [JsonS3UploadLambdaRole, Arn]
