AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  JsonS3UploadLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda-go # file name
      Runtime: go1.x
      CodeUri: lambda/build
      Timeout: 300
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
